services:

  postgres:
    image: postgres:16-alpine
    container_name: deposition-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: deposition
      POSTGRES_USER: deposition
      POSTGRES_PASSWORD: deposition
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - deposition-network

  minio:
    image: minio/minio:latest
    container_name: minio-s3
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: local-dev
      MINIO_ROOT_PASSWORD: local-dev-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    networks:
      - deposition-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://minio:9000 local-dev local-dev-secret; do sleep 2; done;
      /usr/bin/mc mb --ignore-existing local/deposition-local-bucket;
      exit 0;
      "
    networks:
      - deposition-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-sso
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-secret
      KC_DB: dev-file
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8085:8080"
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    command: start-dev
    networks:
      - deposition-network
# curl -X POST http://localhost:8085/realms/deposition/protocol/openid-connect/token -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=deposition-client" -d "username=testuser" -d "password=testuser" -d "grant_type=password"

networks:
  deposition-network:
    driver: bridge
