services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-private-node
    restart: unless-stopped
    command:
      - --network=dev
      - --data-path=/var/lib/besu
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL,DEBUG
      - --host-allowlist=*
      - --rpc-ws-enabled
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8546
      - --rpc-ws-api=ETH,NET,WEB3,TXPOOL,DEBUG
      - --logging=INFO
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data/besu:/var/lib/besu
    networks:
      - deposition-network

  minio:
    image: minio/minio:latest
    container_name: minio-s3
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: local-dev
      MINIO_ROOT_PASSWORD: local-dev-secret
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - ./data/minio:/data
    networks:
      - deposition-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set local http://minio:9000 local-dev local-dev-secret; do sleep 2; done;
      /usr/bin/mc mb --ignore-existing local/deposition-local-bucket;
      exit 0;
      "
    networks:
      - deposition-network

networks:
  deposition-network:
    driver: bridge