spring:
  application:
    name: deposition-system

server:
  port: 8080

integration:
  ethereum:
    rpc-url: http://localhost:8545
    gas-limit-integer: 3000000
    chain-id: 1337
    private-key: "0x3ce6bb8ebb62b6bce60c0bf5cd0407d8f8fc34938e6440f9ebbd49dbf5f52250"
    gas-price-wei: 0
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: local-dev
    secret-key: local-dev-secret
    bucket-name: deposition-local-bucket