spring:
  application:
    name: deposition-system

server:
  port: 8082

integration:
  ethereum:
    rpc-url: http://localhost:18545
    from-address: "0x9b790656b9ec0db1936ed84b3bea605873558198"
    gas-limit-integer: 3000000
    chain-id: 1337
    gas-price-wei: 0
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: local-dev
    secret-key: local-dev-secret
    bucket-name: deposition-local-bucket