spring:
  application:
    name: deposition-system
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}

server:
  port: ${server.port}

integration:
  ethereum:
    rpc-url: ${integration.ethereum.rpc-url}
    gas-limit-integer: ${integration.ethereum.gas-limit-integer}
    chain-id: ${integration.ethereum.chain-id}
    private-key: ${integration.ethereum.private-key}
    gas-price-wei: ${integration.ethereum.gas-price-wei:0}
  s3:
    endpoint: ${integration.s3.endpoint}
    region: ${integration.s3.region}
    access-key: ${integration.s3.access-key}
    secret-key: ${integration.s3.secret-key}
    bucket-name: ${integration.s3.bucket-name}
